# Declaration for terms not available from the RDF gem, mostly local. See config/initializers/terms.rb
# for details of how this manifests in the code.
#
# NOTE: the University of Alberta's local terminology violates standard RDF naming conventions, as normally
# described at (http://www-sop.inria.fr/acacia/personnel/phmartin/RDF/conventions.html#lexicalConventions).
# The primary violations are that we require the terms to appear in the URI in all-lowercase, with no underscores
# or other lexical seperators between word boundaries.
# This was done because <RATIONALE GOES HERE WHEN SOMEONE PROVIDES ONE>
#
# This file is thus structured to map semantically meaningful, idiomatic Ruby method names to the local requirements.
#
# Expected file format:
#    - vocabulary: ual
#      schema: http://terms.library.ualberta.ca/identifiers/
#      terms:
#        doi: doi
#        record_created_in_jupiter: recordcreatedinjupiter
#    - vocabulary: acl
#      schema: http://www.w3.org/ns/auth/acl
#      terms:
#        mode: mode
#
# Usage in the application:
#
#   VOCABULARY[:ual].doi
#   => #<RDF::Vocabulary::Term:0x3fc87891aa0c URI:http://terms.library.ualberta.ca/identifiers/doi>
#

- vocabulary: ual
  schema: http://terms.library.ualberta.ca/
  terms:
    committee_member: commiteeMember
    community: Community # rdf:type for community objects, Zach has advised uppercase for class
    department: department
    depositor: depositor
    dissertant: dissertant
    fedora3_handle: fedora3Handle
    fedora3_uuid: fedora3UUID
    graduation_date: graduationDate
    hydra_noid: hydraNoid
    ingest_batch: ingestBatch
    path: path
    proquest: proquest
    # separate from date_created, we need to track a precise time the metadata record was created
    record_created_in_jupiter: recordCreatedInJupiter
    sitemap_link: sitemapLink
    sort_year: sortYear
    specialization: specialization
    supervisor: supervisor
    thesis_level: thesisLevel
    unicorn: unicorn

- vocabulary: prism
  schema: http://prismstandard.org/namespaces/basic/3.0/
  terms:
    doi: doi

- vocabulary: acl
  schema: 'http://projecthydra.org/ns/auth/acl#'
  terms:
    embargo_history: embargoHistory
    visibility_after_embargo: visibilityAfterEmbargo

- vocabulary: swrc
  schema: 'http://ontoware.org/swrc/ontology#'
  terms:
    institution: institution
